_list:
    @just --list

start +ARGS='':
    just watch run {{ARGS}}

watch CMD='check' +ARGS='':
    watchexec \
        --watch Cargo.toml --watch src \
        --watch ../core/src \
        --restart --clear -- just {{CMD}} {{ARGS}}

cargo +ARGS='':
    cargo {{ARGS}}

run +ARGS='':
    cargo run --bin ai_tester -- {{ARGS}}

check +ARGS='':
    cargo clippy {{ARGS}}

build +ARGS='':
    cargo build {{ARGS}}

test +ARGS='':
    cargo test {{ARGS}}
