[package]
name = "tetra-master-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
tetra-master-core = { path = "../core" }

anyhow = { workspace = true }
clap = { workspace = true }
owo-colors = { workspace = true }
pretty_assertions = { workspace = true }
