[package]
name = "tetra-master-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nanorand = "0.7.0"
nom = "7.1.1"
owo-colors = "3.4.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
test-case = "2.2.1"
