_list:
    @just --list

watch CMD='check' +ARGS='':
    watchexec \
        --watch Cargo.toml --watch src \
        --restart --clear -- just {{CMD}} {{ARGS}}

cargo +ARGS='':
    cargo {{ARGS}}

check +ARGS='':
    cargo clippy {{ARGS}}

test +ARGS='':
    cargo test {{ARGS}}
